FROM hoseinbz/oreka
#FROM centos:6
#
#COPY CentOS-Base.repo /tmp/CentOS-Base.repo
#RUN set -ex && \
#    mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.backup && \
#    mv /tmp/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo && \
#    yum makecache && \
#    yum repolist
#
#RUN set -ex && \
#    date -R && \
#    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
#    cat /etc/localtime && \
#    date -R